source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'8.0'
use_frameworks!
pod 'Alamofire','~>1.2'
pod 'SnapKit','~>0.10.0'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'RDVTabBarController'
pod 'MJExtension'
pod 'AFNetworking'
